IgnoreServerErrors: []
DisableStartupLog: false
DisableInterruptHandler: false
DisableVersionChecker: false
DisablePathCorrection: false
EnablePathEscape: false
EnableOptimizations: false
FireMethodNotAllowed: false
DisableBodyConsumptionOnUnmarshal: false
DisableAutoFireStatusCode: false
TimeFormat: "Mon, Jan 02 2006 15:04:05 GMT"
Charset: UTF-8
TranslateFunctionContextKey: iris.translate
TranslateLanguageContextKey: iris.language
ViewLayoutContextKey: iris.viewLayout
ViewDataContextKey: iris.viewData
RemoteAddrHeaders:
  CF-Connecting-IP: false
  X-Forwarded-For: false
  X-Real-Ip: false
Other: {
  EsUrl: "http://10.0.21.44:9200",
  LogPath: "/Users/tiger/project/logs/xzlan/",
  DbPath: "/Users/tiger/project/logs/go/xzlan.db",
  MailHost: "",
  MailUser: "",
  MailPasword: ""
}
